#!/usr/bin/env php
<?php

use App\Commands\UpdateCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

// Create a new application
$application = new Application();

// Register the Command and make it default
$update_command = new UpdateCommand();
$application->add($update_command);
$application->setDefaultCommand($update_command->getName());

// Run the application
$application->run();
