#!/usr/bin/env php
<?php

use App\Commands\UpdateCommand;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

// Create a new application
$application = new Application();

// Register the Command and make it default
$updateCommand = new UpdateCommand();
$application->add($updateCommand);
$application->setDefaultCommand($updateCommand->getName());

// Run the application
$application->run();
